### PR TITLE
Test the next version of the Zowe VS Code stable branch

### PR DESCRIPTION
**Pull request by phaumer**
With the fix provides by Collin we can now again expand tree views. I merged the changes plus my own update to automatically detect the framework. 

I propose that two other developers try this in Theia and Docker before we merge this into the stable branch for our next build.

### CODE REVIEW

**Comment by lauren-li** [comment]
Tested in:
- Theia (wazi-ide wazi-extras)
- Docker (Build 339, zde-20190830-193858.tar.gz) on Firefox 68.0.1

**Working**
MVS: 
- [x] Folder expand and collapse
- [x] Search and saved search
- [x] Open dataset
- [x] Create new PDS
- [x] Create new PDS member
- [x] Create new sequential DS
- [x] Upload member
- [x] Save edited member
- [x] Save edited sequential DS
- [x] Delete member
- [x] Delete PDS
- [x] Adding and removing favorite
- [x] Progress message for opening large datasets

USS:
- [x] Folder expand and collapse
- [x] Search and saved search
- [x] Open file
- [x] Create new folder
- [x] Create new file
- [x] Upload file
- [x] Save edited file
- [x] Rename file
- [x] Rename folder
- [x] Delete file
- [x] Delete folder
- [x] Adding and removing favorite
- [x] Progress message for opening large files

Notes:
- No refresh buttons for MVS, USS, or Jobs
- Refresh upon create/rename/delete functions sometimes seems spotty, and since the MVS/USS refresh buttons don't appear in the browser, sometimes a whole page refresh is needed to see the change.
- Folders collapse on delete, create, rename, etc.
- No hover tooltip for MVS (although there is in VS Code)
- Had some issues where search icon stops working, but can't consistently recreate this. I will file an issue if I can get recreate steps.

Rename issues (also true within VS Code):
- Rename doesn't seem to check for conflicts before doing the rename, resulting in odd behavior when you rename a folder with an already-existing folder name. (E.g. the renamed folder becomes a child of the already-existing folder with that name.)
- Rename doesn't sync with favorites.

**Review by lauren-li — APPROVED** [review]
Assuming none of the items in the notes section of my comment above are blockers, I think this PR is okay to merge into the stable branch. Most importantly, it addresses the Theia folder expand/collapse issue while bringing in recent improvements.

**Comment by PrasangAPrajapati** [comment]
@phaumer 
Awesome, Everything works in such a smooth way. Only Issue I can see in MVS search filter.

Issue (wazi-ide wazi-extras):
Search for `ZOWEPH` and add as a `Save Search`. Refresh the window and select `ZOWEPH` from Favorites. It should open the datasets starting from `ZOWEPH` but it looks like it's not working.

**Comment by PrasangAPrajapati** [comment]
As we discussed it's not blocking us and search filter history is already there so we might not need that feature anymore.

**Review by PrasangAPrajapati — APPROVED** [review]

**Pull request merged**
